Update build

diff --git a/project/publish b/project/publish
--- a/project/publish
+++ b/project/publish
@@ -1,5 +1,13 @@
 #!/usr/bin/env bash
 
+if [ "$#" -ne 1 ]; then
+  echo "Missing version"
+  exit 1
+fi
+
+git tag -m "Version: $1" "$1"
+git push --follow-tags
+
 # sbt '+ mimaReportBinaryIssues ; tastyMiMaReportIssues ; + publishSigned ; sonatypeBundleRelease'
 sbt '+ mimaReportBinaryIssues ; + publishSigned ; sonatypeBundleRelease'
 
